name: NetNC CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: fedora-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build NetNC Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        tags: netnc:${{ github.sha }}
        push: false
